BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE T_LOC_OBJ FORCE';
  EXECUTE IMMEDIATE 'DROP TYPE T_LOC_TBL FORCE';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/
CREATE OR REPLACE TYPE T_LOC_OBJ AS OBJECT (
  loc NUMBER,
  loc_desc VARCHAR2(100)
);
/
CREATE OR REPLACE TYPE T_LOC_TBL AS TABLE OF T_LOC_OBJ;
/