BEGIN
  --
  EXECUTE IMMEDIATE 'DROP TABLE DEPT CASCADE CONSTRAINTS';
  --
EXCEPTION
  --
  WHEN OTHERS THEN
    --
    NULL;
    --
END;
/
--
CREATE TABLE DEPT (
    dept NUMBER(4) NOT NULL,
    dept_user varchar2(50) NOT NULL
);
--
-- CREATE PRIMARY KEY
ALTER TABLE DEPT ADD CONSTRAINT PK_DEPT PRIMARY KEY (DEPT);