BEGIN
  --
  EXECUTE IMMEDIATE 'DROP TABLE ITEM CASCADE CONSTRAINTS';
  --
EXCEPTION
  --
  WHEN OTHERS THEN
    --
    NULL;
    --
END;
/
--
CREATE TABLE ITEM(
    ITEM VARCHAR2(25) NOT NULL,
    DEPT NUMBER(4) NOT NULL,
    ITEM_DESC VARCHAR2(25) NOT NULL
);
--
-- CREATE PRIMARY KEY
ALTER TABLE ITEM ADD CONSTRAINT PK_ITEM PRIMARY KEY (ITEM);