BEGIN
  --
  EXECUTE IMMEDIATE 'DROP TABLE ITEM_LOC_SOH_SV CASCADE CONSTRAINTS';
  --
EXCEPTION
  --
  WHEN OTHERS THEN
    --
    NULL;
    --
END;
/
--
CREATE TABLE ITEM_LOC_SOH_SV(
    ITEM VARCHAR2(25) NOT NULL,
    LOC NUMBER(10) NOT NULL,
    DEPT NUMBER(4) NOT NULL,
    UNIT_COST NUMBER(20,4) NOT NULL,
    STOCK_ON_HAND NUMBER(12,4) NOT NULL,
    STOCK_VALUE NUMBER(25,4)
    );
--
-- CREATE PRIMARY KEY
ALTER TABLE ITEM_LOC_SOH_SV ADD CONSTRAINT PK_SV_ITEM_LOC PRIMARY KEY (ITEM,LOC);