BEGIN
  --
  EXECUTE IMMEDIATE 'DROP TABLE ITEM_LOC_SOH CASCADE CONSTRAINTS';
  --
EXCEPTION
  --
  WHEN OTHERS THEN
    --
    NULL;
    --
END;
/
--
CREATE TABLE ITEM_LOC_SOH(
ITEM VARCHAR2(25) NOT NULL,
LOC NUMBER(10) NOT NULL,
DEPT NUMBER(4) NOT NULL,
UNIT_COST NUMBER(20,4) NOT NULL,
STOCK_ON_HAND NUMBER(12,4) NOT NULL
);
--
-- CREATE PRIMARY KEY
ALTER TABLE ITEM_LOC_SOH ADD CONSTRAINT PK_ITEM_LOC PRIMARY KEY (ITEM,LOC);