BEGIN
  --
  EXECUTE IMMEDIATE 'DROP TABLE LOC CASCADE CONSTRAINTS';
  --
EXCEPTION
  --
  WHEN OTHERS THEN
    --
    NULL;
    --
END;
/
--
CREATE TABLE LOC(
    LOC NUMBER(10) NOT NULL,
    LOC_DESC VARCHAR2(25) NOT NULL
);
--
-- CREATE PRIMARY KEY
ALTER TABLE LOC ADD CONSTRAINT PK_LOC PRIMARY KEY (LOC);