DELETE FROM ITEM;
--
-- CONNECT BY LEVEL <= 1000 REDUCED TO 100 BECAUSE TABLESPACE ERROR IN ITEM_LOC_SOH TABLE
INSERT INTO ITEM(ITEM,DEPT,ITEM_DESC)
SELECT LEVEL, ROUND(DBMS_RANDOM.VALUE(1,100)), TRANSLATE(DBMS_RANDOM.STRING('A', 20), 'ABCXYZ', LEVEL) FROM DUAL CONNECT BY LEVEL <= 1000;