DELETE FROM ITEM_LOC_SOH;
--
INSERT INTO ITEM_LOC_SOH (ITEM, LOC, DEPT, UNIT_COST, STOCK_ON_HAND)
SELECT ITEM, LOC, DEPT, (DBMS_RANDOM.VALUE(5000,50000)), ROUND(DBMS_RANDOM.VALUE(1000,100000))
FROM ITEM, LOC;