CREATE OR REPLACE PACKAGE PKG_ORC IS
--
  FUNCTION SAVE_ITEM_LOC_SOH_SV(I_LOC  IN     ITEM_LOC_SOH.LOC%TYPE)
    RETURN BOOLEAN;
  --
  FUNCTION GET_LOCATIONS
    RETURN T_LOC_TBL PIPELINED;
  --
  PROCEDURE EXTRACT_STOCK_DATA_TO_CSV;
--
END PKG_ORC;
/